version: '3'
services:
  fastapi:
    build: ./api
    container_name: fastapi_api
    networks:
      - app_network
    ports:
      - "8000:8000"
    volumes:
      - ../../models/model.cb:/app/model.cb

  streamlit:
    build: ./app
    container_name: streamlit_app
    networks:
      - app_network
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi_api:8000/predict

networks:
  app_network:
    driver: bridge
